#all non absolute paths are added up with the directory of the config file
# suppose path: ./my/relative/path -> /path/to/configfile/my/relative/path

cli_timeout_s: 100
grpc_listen_addr: 127.0.0.1:50443
log_file: ./kritis3m_scale.log

cli_log:
  format: text
  log_level: 0
  file: /tmp/cli.log

database:
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "postgres"
    sslmode: "disable"
  log:
    format: text
    log_level: 0

asl_config:
  logging_enabled: true
  log_level: 5

broker_config:
  address: ":8883"
  tcp_only: false
  log:
    format: text
    log_level: 0
  endpoint_config:
    private_key: "/home/philipp/development/kritis3m_workspace/certificates/test_certs/secp384/privateKey.pem"
    device_cert: "/home/philipp/development/kritis3m_workspace/certificates/test_certs/secp384/chain.pem" #device certificate chain
    root_certs:
      - "/home/philipp/development/kritis3m_workspace/certificates/test_certs/secp384/root.pem"
    mutual_authentication: true
    no_encryption: false
    key_exchange_method: "KEX_DEFAULT"
    key_log_file: "./tmp/keylog.txt"
    ciphersuites:
      - "TLS13-AES256-GCM-SHA384"
      - "TLS13-CHACHA20-POLY1305-SHA256"

control_plane_config:
  server_address: ":8883"
  tcp_only: false
  log:
    format: text
    log_level: 0
  endpoint_config:
    private_key: "/home/philipp/development/kritis3m_workspace/certificates/test_certs/secp384/privateKey.pem"
    device_cert: "/home/philipp/development/kritis3m_workspace/certificates/test_certs/secp384/chain.pem" #device certificate chain
    root_certs:
      - "/home/philipp/development/kritis3m_workspace/certificates/test_certs/secp384/root.pem"
    mutual_authentication: true
    no_encryption: false
    key_exchange_method: "KEX_DEFAULT"
    key_log_file: "./tmp/keylog.txt"
    ciphersuites:
      - "TLS13-AES256-GCM-SHA384"
      - "TLS13-CHACHA20-POLY1305-SHA256"

est_server_config:
  server_address: "localhost:8443"
  ca:
    backends:
      - aps: "dataplane"
        certificates: "/home/philipp/development/kritis3m_workspace/certificates/pki/intermediate/ca_chain.pem"
        private_key: "/home/philipp/development/kritis3m_workspace/certificates/pki/intermediate/privateKey.pem"
        pkcs11_module:
          path: "/home/philipp/development/kritis3m_workspace/secure_element/smartcard_middleware.so"
          pin: ""
      - aps: "controlplane"
        certificates: "/home/philipp/development/kritis3m_workspace/certificates/pki/intermediate/ca_chain.pem"
        private_key: "/home/philipp/development/kritis3m_workspace/certificates/pki/intermediate/privateKey.pem"
        pkcs11_module:
          path: "/home/philipp/development/kritis3m_workspace/secure_element/smartcard_middleware.so"
          pin: ""
    default_backend:
      certificates: "/home/philipp/development/kritis3m_workspace/certificates/pki/intermediate/ca_chain.pem"
      private_key: "/home/philipp/development/kritis3m_workspace/certificates/pki/intermediate/privateKey.pem"
      pkcs11_module:
        path: "/home/philipp/development/kritis3m_workspace/secure_element/smartcard_middleware.so"
        pin: ""
    validity: 365
  endpoint_config:
    listen_address: ":8443"
    device_cert: "/home/philipp/development/kritis3m_workspace/certificates/pki/est_server/chain.pem"
    private_key: "/home/philipp/development/kritis3m_workspace/certificates/pki/est_server/privateKey.pem"
    root_certs:
      - "/home/philipp/development/kritis3m_workspace/certificates/pki/root/cert.pem"
    mutual_authentication: true
    key_exchange_method: "KEX_DEFAULT"
    ciphersuites:
      - "TLS13-AES256-GCM-SHA384"
      - "TLS13-CHACHA20-POLY1305-SHA256"
    key_log_file: "/home/philipp/development/kritis3m_workspace/measurements/keylog.log"
    pkcs11:
      path: "/home/philipp/development/kritis3m_workspace/secure_element/smartcard_middleware.so"
      pin: ""
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
    - "[::1]"
  healthcheck_password: "xyzzy"
  rate_limit: 150
  timeout: 30
  log:
    format: text
    log_level: 0 
  asl_config:
    logging_enabled: true
    log_level: 5

acl_policy_path: ./startup.json
