#all non absolute paths are added up with the directory of the config file
# suppose path: ./my/relative/path -> /path/to/configfile/my/relative/path
node_server:
  address: ":8080"
  log:
    log_level: debug
    mode: debug # release debug test
  endpoint_config:
    private_key: "./certs/privateKey.pem"
    device_cert: "./certs/chain.pem" #device certificate chain
    root_cert: "./certs/root.pem"
    mutual_authentication: true
    no_encryption: false
    key_exchange_method: "KEX_DEFAULT"
    key_log_file: "./tmp/keylog.txt"

database:
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "postgres"
    sslmode: "disable"
  log:
    format: text
    log_level: 1

asl_config:
  logging_enabled: true
  log_level: 4

broker_config:
  address: ":8883"
  log:
    format: text
    log_level: 1
  endpoint_config:
    private_key: "./certs/privateKey.pem"
    device_cert: "./certs/chain.pem" #device certificate chain
    root_cert: "./certs/root.pem"
    mutual_authentication: true
    no_encryption: false
    key_exchange_method: "KEX_DEFAULT"
    key_log_file: "./tmp/keylog.txt"

control_plane_config:
  server_address: ":8080"
  log:
    format: text
    log_level: 1
  endpoint_config:
    private_key: "./certs/privateKey.pem"
    device_cert: "./certs/chain.pem" #device certificate chain
    root_cert: "./certs/root.pem"
    mutual_authentication: true
    no_encryption: false
    key_exchange_method: "KEX_DEFAULT"
    key_log_file: "./tmp/keylog.txt"

acl_policy_path: ./startup.json
